SPH/Controllers/DiariesController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg;
using SPH.Models;
using SPH.Persistence;
using SPH.Repositories.Interfaces;
using SPH.Utilities;

namespace SPH.Controllers
{
    [Authorize]
    public class DiariesController : Controller
    {
        private readonly IUnitWork _unitWork;
        private readonly SPHDbContext _context;

        public DiariesController(IUnitWork unitWork, SPHDbContext context)
        {
            _unitWork = unitWork;
            _context = context;
        }

        private int GetUserId()
        {
            var claimuser = HttpContext.User;
            int userId = 0;
            if (claimuser.Identity.IsAuthenticated)
            {
                userId = int.Parse(claimuser.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value);
            }
            return userId;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString)
        {
            try
            {
                int userId = GetUserId();
                ViewData["UserId"] = userId;

                var notes = await _unitWork.diary.GetUserNotesAsync(userId);

                if (!String.IsNullOrEmpty(searchString))
                {
                    notes = notes.Where(n => n.NombreNota.Contains(searchString, StringComparison.OrdinalIgnoreCase));
                }
                ViewData["CurrentFilter"] = searchString;
                return View(notes);
            }
            catch (Exception ex)
            {
                TempData[DS.Error] = "Se produjo un error al obtener las notas.";
                return View("Error");
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            var diary = new Diary
            {
                FechaCreacion = DateTime.Now,
                UserId = GetUserId()
            };
            return View(diary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Diary diary)
        {
            if (!ModelState.IsValid)
            {
                return View(diary); // Retornamos la vista con el modelo en caso de error
            }

            diary.FechaCreacion = DateTime.Now;
            diary.UserId = GetUserId();

            await _unitWork.diary.AgregarAsync(diary);
            await _unitWork.GuardarAsync();
            TempData[DS.Successful] = "Nota creada correctamente.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diary = await _unitWork.diary.ObtenerAsync(id.GetValueOrDefault());
            if (diary == null)
            {
                return NotFound();
            }

            return View(diary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Diary diary)
        {
            if (!ModelState.IsValid)
            {
                return View(diary); // Retornamos la vista con el modelo en caso de error
            }

            if (id != diary.NoteId)
            {
                return NotFound();
            }

            try
            {
                _unitWork.diary.Actualizar(diary);
                await _unitWork.GuardarAsync();
                TempData[DS.Successful] = "Nota actualizada correctamente.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View(diary); // Retornamos la vista con el modelo en caso de excepción
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diary = await _unitWork.diary.ObtenerAsync(id.GetValueOrDefault());
            if (diary == null)
            {
                return NotFound();
            }
            return View(diary);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var diary = await _unitWork.diary.ObtenerAsync(id.GetValueOrDefault());
            if (diary == null)
                return NotFound();
            return View(diary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                var diary = await _unitWork.diary.ObtenerAsync(id);
                return View(diary); // Retornamos la vista con el modelo en caso de error
            }

            var diaryToDelete = await _unitWork.diary.ObtenerAsync(id);
            if (diaryToDelete == null)
            {
                return Json(new { success = false, message = "Nota no encontrada." });
            }

            _unitWork.diary.Eliminar(diaryToDelete);
            await _unitWork.GuardarAsync();

            return Json(new { success = true, message = "Nota eliminada correctamente." });
        }

        [HttpPost]
        public async Task<IActionResult> AutoSave(Diary diary)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, message = "Error al guardar automáticamente." });
            }

            if (diary.NoteId == 0) // Nueva nota
            {
                diary.FechaCreacion = DateTime.Now;
                await _unitWork.diary.AgregarAsync(diary);
            }
            else // Editando nota existente
            {
                var existingDiary = await _unitWork.diary.ObtenerAsync(diary.NoteId);
                if (existingDiary != null)
                {
                    existingDiary.NombreNota = diary.NombreNota;
                    existingDiary.Descripcion = diary.Descripcion;
                    // actualiza otros campos si es necesario
                    _unitWork.diary.Actualizar(existingDiary);
                }
            }

            await _unitWork.GuardarAsync();
            return Json(new { success = true, message = "Guardado automático realizado." });
        }
    }
}

SPH/Controllers/MessengersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SPH.Models;
using SPH.Repositories.Interfaces;
using SPH.Utilities;
using System.Security.Claims;

namespace SPH.Controllers
{
    [Authorize]
    public class MessengersController : Controller
    {
        private readonly IUnitWork _unitWork;

        public MessengersController(IUnitWork unitWork)
        {
            _unitWork = unitWork;
        }

        private int GetUserId()
        {
            var claimUser = HttpContext.User;
            int userId = 0;
            if (claimUser.Identity.IsAuthenticated)
            {
                userId = int.Parse(claimUser.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value);
            }
            return userId;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            int userId = GetUserId();
            ViewData["UserId"] = userId;

            var contacts = await _unitWork.messenger.GetUserContactsAsync(userId);
            return View(contacts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var messenger = new Messenger
            {
                UserId = GetUserId()
            };
            return View(messenger);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Messenger messenger)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _unitWork.messenger.AgregarAsync(messenger);
                    await _unitWork.GuardarAsync();

                    return Json(new { success = true, message = "Contacto agregado correctamente." });
                }
                catch (Exception)
                {
                    return Json(new { success = false, message = "Error al agregar el contacto, intente de nuevo." });
                }
            }

            return Json(new { success = false, message = "Error en los datos del formulario. Verifique los campos e intente de nuevo." });
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var messenger = await _unitWork.messenger.ObtenerAsync(id.GetValueOrDefault());
            if (messenger == null)
            {
                return NotFound();
            }

            return View(messenger);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string content)
        {
            var message = await _unitWork.message.ObtenerAsync(id);
            if (message == null)
            {
                return Json(new { success = false, message = "Mensaje no encontrado." });
            }

            try
            {
                message.Content = content; // Actualizar el contenido del mensaje

                _unitWork.message.Actualizar(message);
                await _unitWork.GuardarAsync();

                return Json(new { success = true, message = "Mensaje editado correctamente." });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "Error al editar el mensaje. Inténtelo de nuevo más tarde." });
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messenger = await _unitWork.messenger.ObtenerAsync(id.GetValueOrDefault());
            if (messenger == null)
            {
                return NotFound();
            }

            return View(messenger);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var messenger = await _unitWork.messenger.ObtenerAsync(id.GetValueOrDefault());
            if (messenger == null)
                return NotFound();

            return View(messenger);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var messenger = await _unitWork.messenger.ObtenerAsync(id);
            if (messenger == null)
            {
                return Json(new { success = false, message = "Contacto no encontrado." });
            }

            _unitWork.messenger.Eliminar(messenger);
            await _unitWork.GuardarAsync();

            return Json(new { success = true, message = "Contacto eliminado correctamente." });
        }

    }
}

SPH/Controllers/ThemesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SPH.Models;
using SPH.Repositories.Interfaces;
using System.Security.Claims;

namespace SPH.Controllers
{
    [Authorize]
    public class ThemesController : Controller
    {
        private readonly IUnitWork _unitWork;

        public ThemesController(IUnitWork unitWork)
        {
            _unitWork = unitWork;
        }

        public async Task<IActionResult> Index()
        {
            var themes = await _unitWork.theme.ObtenerTodosAsync();
            return View(themes);
        }

        public async Task<IActionResult> Details(int id)
        {
            var theme = await _unitWork.theme.ObtenerAsync(id);
            if (theme == null)
            {
                return NotFound();
            }
            return View(theme);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Theme theme)
        {
            if (ModelState.IsValid)
            {
                theme.UserId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
                await _unitWork.theme.AgregarAsync(theme);
                await _unitWork.GuardarAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(theme);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var theme = await _unitWork.theme.ObtenerAsync(id);
            if (theme == null)
            {
                return NotFound();
            }
            return View(theme);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Theme theme)
        {
            if (id != theme.ThemeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitWork.theme.Actualizar(theme);
                    await _unitWork.GuardarAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await _unitWork.theme.ObtenerAsync(theme.ThemeId) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(theme);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var theme = await _unitWork.theme.ObtenerAsync(id);
            if (theme == null)
            {
                return NotFound();
            }
            return View(theme);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var theme = await _unitWork.theme.ObtenerAsync(id);
            _unitWork.theme.Eliminar(theme);
            await _unitWork.GuardarAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ApplyTheme(int id)
        {
            var theme = await _unitWork.theme.ObtenerAsync(id);
            if (theme == null)
            {
                return Json(new { success = false, message = "Tema no encontrado" });
            }
            HttpContext.Session.SetInt32("AppliedThemeId", id);
            return Json(new { success = true });
        }
    }
}

SPH/Views/Users/Details.cshtml
@model SPH.Models.User

<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet"> <!-- Font Awesome para íconos -->
    <link rel="stylesheet" href="~/css/configuracion.css">
</head>

<!-- ============ Container ============ -->
<div class="container">

    <!-- ============ Navigation ============ -->
    <nav class="navigation">
        <ul>
            <!-- Logo -->
            <li class="logo">
                <a href="@Url.Action("Index", "Home")">
                    <span class="icon">
                        <ion-icon name="logo-apple"></ion-icon>
                    </span>
                    <span class="title">Student Planner Hub</span>
                </a>
            </li>

            <!-- Navigation Links -->
            <li>
                <a href="@Url.Action("Index","Home")">
                    <span class="icon"><ion-icon name="home-outline"></ion-icon></span>
                    <span class="title">Inicio</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Calendaries")">
                    <span class="icon"><ion-icon name="calendar-outline"></ion-icon></span>
                    <span class="title">Calendario</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Diaries")">
                    <span class="icon"><ion-icon name="book-outline"></ion-icon></span>
                    <span class="title">Agenda</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Organizers")">
                    <span class="icon"><ion-icon name="clipboard-outline"></ion-icon></span>
                    <span class="title">Organizador</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Messengers")">
                    <span class="icon"><ion-icon name="chatbubble-outline"></ion-icon></span>
                    <span class="title">Mensajería</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Themes")">
                    <span class="icon"><ion-icon name="brush-outline"></ion-icon></span>
                    <span class="title">Personalizar Tema</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Details", "Users")">
                    <span class="icon"><ion-icon name="settings-outline"></ion-icon></span>
                    <span class="title">Configurar</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("LogOut", "Home")">
                    <span class="icon"><ion-icon name="log-out-outline"></ion-icon></span>
                    <span class="title">Cerrar Sesión</span>
                </a>
            </li>
        </ul>
    </nav>

    <!-- ============ Main Content ============ -->
    <div class="main">
        <!-- Topbar -->
        <div class="topbar">
            <!-- Toggle Button -->
            <div class="toggle">
                <ion-icon name="menu-outline"></ion-icon>
            </div>
        </div>

        <!-- ======================= Contenido Principal ================== -->
        <div class="content" id="content">
            <h2 class="mb-4">Detalles de Usuario</h2>
            <div class="card">
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Nombre:</h4>
                            <p class="card-text">@Model.Nombre</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">NickName:</h4>
                            <p class="card-text">@Model.NickName</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Edad:</h4>
                            <p class="card-text">@Model.Edad</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">Correo:</h4>
                            <p class="card-text">@Model.Correo</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Fecha de Nacimiento:</h4>
                            <p class="card-text">@Model.FechaNacimiento.ToShortDateString()</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">Imagen de Perfil:</h4>
                            <p class="card-text">@Model.ImagenPerfil</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Biografía:</h4>
                            <p class="card-text">@Model.Biografia</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">Número de Contacto:</h4>
                            <p class="card-text">@Model.NumeroContacto</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Ubicación:</h4>
                            <p class="card-text">@Model.Ubicacion</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">Rol:</h4>
                            <p class="card-text">@Model.Rol</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4 class="card-title">Estado:</h4>
                            <p class="card-text">@Model.Estado</p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="card-title">Organización:</h4>
                            <p class="card-text">@Model.Organizacion</p>
                        </div>
                    </div>
                </div>
            </div>
            <p class="mt-4">
                <a asp-action="Edit" asp-controller="Users" class="btn btn-primary">Editar</a>
            </p>
        </div>
    </div>
</div>

@section Scripts {
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/js/sidebar.js"></script>


    <script>
        const toggle = document.querySelector('.toggle');
        const navigation = document.querySelector('.navigation');
        const main = document.querySelector('.main');

        toggle.onclick = function () {
            navigation.classList.toggle('active');
            main.classList.toggle('active');
        };
    </script>
}

SPH/Views/Users/Edit.cshtml
@model SPH.Models.User

<h1>Editar Usuario</h1>

<div class="card-body">
    <form asp-action="Edit">
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NickName" class="control-label"></label>
            <input asp-for="NickName" class="form-control" />
            <span asp-validation-for="NickName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Edad" class="control-label"></label>
            <input asp-for="Edad" class="form-control" />
            <span asp-validation-for="Edad" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Correo" class="control-label"></label>
            <input asp-for="Correo" class="form-control" />
            <span asp-validation-for="Correo" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Contraseña" class="control-label"></label>
            <input asp-for="Contraseña" type="password" class="form-control" />
            <span asp-validation-for="Contraseña" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="FechaNacimiento" class="control-label"></label>
            <input asp-for="FechaNacimiento" type="date" class="form-control" />
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>

        <!-- Campos ocultos -->
        <div class="form-group hide">
            <label asp-for="Rol" class="control-label"></label>
            <input asp-for="Rol" class="form-control" />
            <span asp-validation-for="Rol" class="text-danger"></span>
        </div>
        <div class="form-group hide">
            <label asp-for="Estado" class="control-label"></label>
            <input asp-for="Estado" class="form-control" />
            <span asp-validation-for="Estado" class="text-danger"></span>
        </div>
        <!-- Fin campos ocultos -->

        <div class="form-group">
            <label asp-for="ImagenPerfil" class="control-label"></label>
            <input asp-for="ImagenPerfil" class="form-control" />
            <span asp-validation-for="ImagenPerfil" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Biografia" class="control-label"></label>
            <textarea asp-for="Biografia" class="form-control"></textarea>
            <span asp-validation-for="Biografia" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumeroContacto" class="control-label"></label>
            <input asp-for="NumeroContacto" class="form-control" />
            <span asp-validation-for="NumeroContacto" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Ubicacion" class="control-label"></label>
            <input asp-for="Ubicacion" class="form-control" />
            <span asp-validation-for="Ubicacion" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Organizacion" class="control-label"></label>
            <input asp-for="Organizacion" class="form-control" />
            <span asp-validation-for="Organizacion" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        <div>
            <a asp-action="Details" class="btn btn-secondary">Volver</a>
        </div>
    </form>
</div>

SPH/Views/Users/Login.cshtml
@{
    ViewData["Title"] = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/flatly/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/login.css">
</head>
<body>
    <main>
        <div class="box">
            <div class="inner-box">
                <div class="forms-wrap">
                    <form asp-controller="Users" asp-action="Login" method="post" class="sign-in-form">
                        <div class="logo">
                            <img src="./images/logo.png" alt="Student Planner Hub" />
                            <h4>Student Planner Hub</h4>
                        </div>

                        <div class="heading">
                            <h2>Bienvenido de nuevo</h2>
                            <h6>¿Aún no estás registrado?</h6>
                            <a href="@Url.Action("Register","Users")" class="toggle">Sign up</a>
                        </div>

                        <div class="actual-form">
                            <div class="input-wrap">
                                <input type="email" placeholder="Correo" required name="email" class="input-field" autocomplete="on" />
                                <i class='bx bxs-user'></i>
                            </div>

                            <div class="input-wrap">
                                <input type="password" placeholder="Contraseña" required name="clave" class="input-field" autocomplete="on" />
                                <i class='bx bxs-lock-alt'></i>
                            </div>

                            <input type="submit" value="Iniciar Sesión" class="sign-btn btn" />

                            @if (ViewData["Mensaje"] != null)
                            {
                                <p class="text">
                                    @ViewData["Mensaje"]
                                </p>
                            }
                        </div>
                    </form>
                </div>

                <!-- Carrusel de imágenes y textos -->
                <div class="carousel">
                    <div class="images-wrapper">
                        <img src="./images/img1.jpeg" class="image img-1 show" alt="Image 1" />
                        <img src="./images/img2.jpeg" class="image img-2" alt="Image 2" />
                        <img src="./images/img3.jpeg" class="image img-3" alt="Image 3" />
                    </div>

                    <div class="text-slider">
                        <div class="text-wrap">
                            <div class="text-group">
                                <h2>Create your own courses</h2>
                                <h2>Customize as you like</h2>
                                <h2>Invite students to your class</h2>
                            </div>
                        </div>

                        <div class="bullets">
                            <span class="active" data-value="1"></span>
                            <span data-value="2"></span>
                            <span data-value="3"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Scripts para el carrusel de imágenes
            const images = document.querySelectorAll('.image');
            const bullets = document.querySelectorAll('.bullets span');
            const textGroup = document.querySelector('.text-group');
            let currentIndex = 0;

            function showSlide(index) {
                images.forEach((img, i) => {
                    img.classList.toggle('show', i === index);
                });
                bullets.forEach((bullet, i) => {
                    bullet.classList.toggle('active', i === index);
                });
                textGroup.style.transform = `translateY(-${index * 100}%)`;
            }

            bullets.forEach((bullet, index) => {
                bullet.addEventListener('click', () => {
                    currentIndex = index;
                    showSlide(currentIndex);
                });
            });

            // Auto-play (opcional)
            setInterval(() => {
                currentIndex = (currentIndex + 1) % images.length;
                showSlide(currentIndex);
            }, 5000); // Cambia cada 5 segundos
        });
    </script>

    <script src="~/js/login.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>